import { Select } from '@material-ui/core';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import Button from '../components/button';
import Header from '../components/header';
import TimeField from '../components/timeField';
import styles from '../styles/Home.module.css';

export default function Home() {
    const days = ['Monday', 'Tuesday', 'Wednesday', 'Thrusday', 'Friday', 'Saturday', 'Sunday'];
    const [daysSelected, setDaysSelected] = useState([]);
    const [data, setData] = useState([]);
    const [from, setFrom] = useState('00:00:00');
    const [too, setToo] = useState('00:00:00');

    console.log(data);

    const getTime = (e) => {
        setFrom(e.target.value);
    };
    const getTimeToo = (e) => {
        setToo(e.target.value);
    };

    const select = (day) => {
        if (daysSelected.find((element) => element === day)) {
            const array = daysSelected.filter((ele) => {
                return ele != day;
            });
            console.log(day);
            console.log(array);
            console.log(daysSelected);
            setDaysSelected(array);
        } else {
            setDaysSelected((daysSelected) => [...daysSelected, day]);
        }
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <main className={styles.main}>
                <h1>List your Venue</h1>
                <h2>Venue open timings</h2>
                <div className="wrapper">
                    <div className="days">
                        {days.map((day) => {
                            if (daysSelected.find((element) => element === day)) {
                                return <Button day={day} key={day} click={select} clas="day_button" />;
                            } else {
                                return <Button day={day} key={day} click={select} />;
                            }
                        })}
                    </div>
                    <div className="fields">
                        {days.map((day) => {
                            if (daysSelected.find((element) => element === day)) {
                                return <TimeField key={day} value={from} change={getTime} disable={false} />;
                            } else {
                                return <TimeField key={day} value={from} change={getTime} disable={true} />;
                            }
                        })}
                    </div>
                    <div className="fields_too">
                        {days.map((day) => {
                            if (daysSelected.find((element) => element === day)) {
                                return <TimeField key={day} value={too} change={getTimeToo} disable={false} />;
                            } else {
                                return <TimeField key={day} value={too} change={getTimeToo} disable={true} />;
                            }
                        })}
                    </div>
                </div>
                <div className="submit_butoon">
                    <button className="submit">Submit</button>
                </div>
            </main>

            <footer className={styles.footer}>
                <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}
